---
max_opts: 1000
eval_episodes: 1
eval_threshold: ~
model_dir: "./border/examples/model/dqn_PongNoFrameskip-v4_debug"
opt_interval: 100
eval_interval: 50000
record_interval: 100
save_interval: 500000
