---
model_config:
  feature_dim: 3136
  embed_dim: 64
  f_config:
    n_stack: 4
    out_dim: 3136
    skip_linear: true
  m_config:
    in_dim: 3136
    units:
      - 512
    out_dim: 0
  opt_config:
    Adam:
      lr: 0.00001
soft_update_interval: 10000
n_updates_per_opt: 1
min_transitions_warmup: 2500
batch_size: 32
discount_factor: 0.99
tau: 1.0
train: false
explorer:
  EpsilonGreedy:
    n_opts: 0
    eps_start: 1.0
    eps_final: 0.02
    final_step: 1000000
sample_percents_pred: Uniform64
sample_percents_tgt: Uniform64
sample_percents_act: Uniform32
device: ~
phantom: ~
