[package]
name = "border"
version = "0.0.0"
authors = ["Taku Yoshioka <taku.yoshioka.4096@gmail.com>"]
edition = "2018"

description = "Reinforcement learning library"
repository = "https://github.com/taku-y/border"
keywords = ["reinforcement learning"]
categories = ["science"]
license = "MIT OR Apache-2.0"
readme = "README.md"

[dependencies]
ndarray = { version = "0.14", features = ["serde"] }
tch = "0.3.0"
numpy = "0.13"
pyo3 = "0.13"
fastrand = "1.4.0"
log = "0.4"
env_logger = "0.8.2"
rayon = "1.1"
num-traits = "0.2.14"
chrono = "0.4"
tensorboard-rs = "0.2.4"
thiserror = "1.0"

[dev-dependencies]
clap = "2.33.3"
csv = "1.1.5"
serde = { version = "1.0.117", features = ["derive"] }
anyhow = "1.0.38"
