[workspace]

members = [
    "border-core",
    "border-py-gym-env",
    "border-tch-agent",
    "border-derive",
    "border-atari-env",
    "border-async-trainer",
    "border"
]
exclude = ["docker/"]
