[package]
name = "lrr"
version = "0.1.0"
authors = ["taku-y <taku.yoshioka.4096@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.14"
tch = "0.3.0"
numpy = "0.13"
pyo3 = "0.13"
fastrand = "1.4.0"

# [features]
# python = ["pyo3"]

# [[example]]
# name = "test1"
# required-features = ["python"]
