[package]
name = "border"
version = "0.0.5"
authors = ["Taku Yoshioka <yoshioka@laboro.ai>"]
edition = "2018"
rust-version = "1.68.2"

description = "Reinforcement learning library"
repository = "https://github.com/taku-y/border"
keywords = ["rl"]
categories = ["science"]
license = "GPL-2.0-or-later"
readme = "README.md"
autoexamples = false

[dependencies]
aquamarine = { workspace = true }
tch = { workspace = true, optional = true }
border-async-trainer = { version = "0.0.5", path = "../border-async-trainer", optional = true }
anyhow = { workspace = true }
log = { workspace = true }
dirs = { workspace = true }
zip = "0.5.12"
reqwest = { version = "0.11.3", features = ["blocking"] }
border-core = { version = "0.0.5", path = "../border-core" }

[[example]]
name = "dqn_cartpole"
required-features = ["tch"]
test = true

[[example]]
name = "iqn_cartpole"
required-features = ["tch"]
test = true

[[example]]
name = "sac_pendulum"
required-features = ["tch"]
test = true

[[example]]
name = "sac_lunarlander_cont"
required-features = ["tch"]
test = false

# [[example]]
# name = "random_atari"
# required-features = ["tch"]
# test = false

[[example]]
name = "dqn_atari"
path = "examples/atari/dqn_atari.rs"
required-features = ["tch"]
test = false

[[example]]
name = "dqn_atari_async"
path = "examples/atari/dqn_atari_async.rs"
required-features = ["tch", "border-async-trainer"]
test = false

[[example]]
name = "sac_fetch_reach"
path = "examples/gym-robotics/sac_fetch_reach.rs"
required-features = ["tch"]
test = false

[[example]]
name = "iqn_atari_rs"
required-features = ["tch"]
test = false

[[example]]
name = "sac_ant"
required-features = ["tch"]
test = false

[[example]]
name = "sac_ant_async"
required-features = ["tch", "border-async-trainer"]
test = false

[[example]]
name = "make_cfg_dqn_atari"
required-features = ["border-async-trainer"]
test = false

[[example]]
name = "make_cfg_iqn_atari"
required-features = ["border-async-trainer"]
test = false

[dev-dependencies]
clap = { workspace = true }
csv = { workspace = true }
tempdir = { workspace = true }
border-derive = { version = "0.0.5", path = "../border-derive" }
border-core = { version = "0.0.5", path = "../border-core" }
border-tensorboard = { version = "0.0.5", path = "../border-tensorboard" }
border-tch-agent = { version = "0.0.5", path = "../border-tch-agent" }
border-py-gym-env = { version = "0.0.5", path = "../border-py-gym-env" }
border-atari-env = { version = "0.0.5", path = "../border-atari-env" }
serde = { workspace = true, features = ["derive"] }
crossbeam-channel = { workspace = true }
env_logger = { workspace = true }
numpy = { workspace = true }
ndarray = { workspace = true, features = ["serde"] }
num-traits = { workspace = true }
pyo3 = { workspace = true, default-features = false }
fastrand = { workspace = true }
chrono = { workspace = true }
tensorboard-rs = { workspace = true }
thiserror = { workspace = true }
serde_yaml = { workspace = true }

[package.metadata.docs.rs]
features = ["doc-only"]

[features]
# default = [ "adam_eps" ]
doc-only = ["tch/doc-only"]
adam_eps = []

#[target.'cfg(feature="adam_eps")'.patch.crates-io]
#tch = { git = "https://github.com/taku-y/tch-rs", branch = "adam_eps" }
