[package]
name = "border-atari-env"
version = "0.0.5"
authors = ["Taku Yoshioka <taku.yoshioka.4096@gmail.com>"]
edition = "2018"

description = "Atari environment based on gym-rs"
repository = "https://github.com/taku-y/border"
keywords = ["rl"]
categories = ["science"]
license = "MIT OR Apache-2.0"
readme = "README.md"
autoexamples = false

[dependencies]
anyhow = "1.0.38"
pixels = "0.2.0"
winit = "0.24.0"
atari-env = { version = "0.1.1", path = "../../../elbaro/gym-rs/atari-env" }
dirs = "3.0.1"
border-core = { version = "0.0.5", path = "../border-core" }
image = "0.23.14"
tch = { version = "0.5.0", optional = true }
serde = { version = "=1.0.126", features = ["derive"] }

[[example]]
name = "random_pong"

[dev-dependencies]
fastrand = "1.4.0"
env_logger = "0.8.2"
