---
feature_dim: 3136
embed_dim: 64
f_config:
  n_stack: 4
  feature_dim: 3136
m_config:
  in_dim: 3136
  hidden_dim: 512
  out_dim: 0
opt_config:
  Adam:
    lr: 0.00005
  # AdamEps:
  #   lr: 0.00005
  #   eps: 0.0003125
phantom: ~
